/**
 * Curated advice list. Edit freely — short, concrete, slightly contrarian
 * is the vibe. Avoid platitudes. One sentence each is ideal.
 */
export const advice: string[] = [
  // doing things
  "If a small task takes less than two minutes, just do it now.",
  "Send the message you're avoiding. The longer it sits, the heavier it gets.",
  "If you can't decide between two options, pick the one that makes a better story.",
  "Sleep on it before sending the angry reply.",
  "Walk for ten minutes outside before opening your laptop in the morning.",
  "If a meeting could have been an email, kindly cancel it.",
  "Save the receipt. You will need it.",
  "Make the next step smaller than feels reasonable.",
  "Don't optimize what you haven't built yet.",
  "If you've read three articles on the topic, stop reading and try the thing.",
  "If you don't know where to start, start with what's in front of you.",
  "Stop refreshing. Close the tab.",
  "Write the email subject last.",
  "Schedule the boring appointment. Today.",
  "When stuck on a problem, explain it out loud to someone — or to nobody.",
  "The first ten minutes of a task are the hardest. Sit through them.",
  "Set the deadline before you start. You'll work to fill the time you give it.",
  "Print the document and read it on paper. You'll catch what the screen hides.",
  "If you're stuck reading, start writing. If you're stuck writing, take a walk.",
  "Two hours of focus beats eight hours of distraction.",
  "If you keep losing it, give it a permanent home.",
  "Label the cables.",
  "Back up the photos. Today.",
  "The thing you keep meaning to fix usually takes twenty minutes.",
  "Take five minutes at the end of the day to put things back where they live.",

  // money
  "Don't buy the upgrade. The current one is fine.",
  "Read the contract before you sign it. Twice.",
  "Ask for the discount. The worst they can say is no.",
  "Pay people back the same day, even small amounts.",
  "Wait three days before buying anything that's not food. Most wants pass.",
  "Cancel the subscription you opened just to try.",
  "Tip in cash when you can.",
  "The cheap version is usually fine the first time. Buy the good one when you wear it out.",
  "Keep a little cash on you. Not every machine takes a card.",
  "Track every krona for one month. You'll never see your spending the same way.",

  // body
  "Drink a glass of water before you decide you're tired.",
  "Take the stairs.",
  "Move your body before you check your phone.",
  "If you're tired and frustrated, eat something.",
  "Floss the ones you want to keep.",
  "Charge your devices in the kitchen, not the bedroom.",
  "Put your phone in another room while you eat.",
  "Sun in your eyes for ten minutes in the morning beats most coffee.",
  "Stretch the side that feels tighter — twice as long as the other.",
  "A cold shower at the end is shorter than you think.",
  "Eat the protein first.",
  "Don't wait until you're tired to lie down.",
  "Sit in silence for five minutes before bed.",
  "Put your running shoes by the door before you go to sleep.",
  "Make your bed. Every morning. Yes, it matters.",

  // people
  "Compliment people out loud. It costs nothing and changes rooms.",
  "If a friend keeps making you feel small, see them less.",
  "Apologize cleanly. Don't add a defence.",
  "If you find yourself rehearsing a conversation, have it.",
  "Send the photo while it's still fresh.",
  "Ask \"how are you, really?\" and wait for the second answer.",
  "If you're thinking about them, tell them.",
  "Visit your parents now, while they're still annoyed by it.",
  "Listen for what's not being said.",
  "If you're irritable around someone every time, the pattern is the data.",
  "It's okay to leave the party early.",
  "Save the praise for in-person.",
  "Cook one extra portion. Future you will be grateful.",

  // thinking
  "Most things you're worried about will not happen. Plan for the ones that might.",
  "When in doubt, ask one specific question.",
  "Notice when your environment is the problem, not your willpower.",
  "Boring habits beat exciting plans.",
  "Boredom is a signal, not a problem.",
  "Most procrastination is fear in a costume.",
  "Strong opinions, loosely held — emphasis on loosely.",
  "If you can't explain it to yourself in plain words, you don't understand it yet.",
  "Ask \"and then what?\" three times before committing.",
  "When tired, defer the decision.",
  "The simple solution is usually the right one — and rarely the obvious one.",
  "If two paths look equal, pick the one with more upside.",
  "What would you tell a friend in your situation? Do that.",
  "Don't trust advice that's selling you something.",
  "The story that explains everything is usually wrong.",
  "Most disagreements are about definitions, not values.",
  "If a rule keeps tripping you up, the rule might be wrong.",

  // small specific
  "Take a photo of the parking spot.",
  "Wash the bottle before you put it away.",
  "Empty the bag at the end of the day.",
  "Rotate the towels — old ones to gym, new ones to bath.",
  "Check the tire pressure once a season.",
  "Put on real clothes, even on the days you're staying in.",
];
