/**
 * Curated advice list. Edit freely — short, concrete, slightly contrarian
 * is the vibe. Avoid platitudes. One sentence each is ideal.
 */
export const advice: string[] = [
  "If a small task takes less than two minutes, just do it now.",
  "Drink a glass of water before you decide you're tired.",
  "Send the message you're avoiding. The longer it sits, the heavier it gets.",
  "If you can't decide between two options, pick the one that makes a better story.",
  "Sleep on it before sending the angry reply.",
  "Walk for ten minutes outside before opening your laptop in the morning.",
  "When you're stuck, lower the bar. Write the bad version first.",
  "If a meeting could have been an email, kindly cancel it.",
  "Save the receipt. You will need it.",
  "Don't buy the upgrade. The current one is fine.",
  "Take the stairs.",
  "Read the contract before you sign it. Twice.",
  "Ask for the discount. The worst they can say is no.",
  "Compliment people out loud. It costs nothing and changes rooms.",
  "Most things you're worried about will not happen. Plan for the ones that might.",
  "Pay people back the same day, even small amounts.",
  "If you keep losing it, give it a permanent home.",
  "Cook one extra portion. Future you will be grateful.",
  "Put your phone in another room while you eat.",
  "If you don't know where to start, start with what's in front of you.",
  "Boring habits beat exciting plans.",
  "When in doubt, ask one specific question.",
  "Apologize cleanly. Don't add a defense.",
  "If you find yourself rehearsing a conversation, have it.",
  "Don't optimize what you haven't built yet.",
  "Move your body before you check your phone.",
  "If you've read three articles on the topic, stop reading and try the thing.",
  "Notice when your environment is the problem, not your willpower.",
  "Make the next step smaller than feels reasonable.",
  "Charge your devices in the kitchen, not the bedroom.",
  "Write the email subject last.",
  "If you're tired and frustrated, eat something.",
  "Schedule the boring appointment. Today.",
  "Stop refreshing. Close the tab.",
  "It's okay to leave the party early.",
  "If a friend keeps making you feel small, see them less.",
  "Take a photo of the parking spot.",
  "Set a 25-minute timer and just begin.",
  "When stuck on a problem, explain it out loud to someone — or to nobody.",
  "Floss the ones you want to keep.",
];
