export type EmojiEntry = {
  char: string;
  name: string;
  keywords: string[];
  category: Category;
};

export type Category =
  | "smileys"
  | "people"
  | "love"
  | "animals"
  | "food"
  | "travel"
  | "activity"
  | "objects"
  | "nature"
  | "symbols";

export const CATEGORIES: { id: Category; label: string }[] = [
  { id: "smileys", label: "Smileys" },
  { id: "people", label: "People" },
  { id: "love", label: "Love" },
  { id: "animals", label: "Animals" },
  { id: "food", label: "Food" },
  { id: "travel", label: "Travel" },
  { id: "activity", label: "Activity" },
  { id: "objects", label: "Objects" },
  { id: "nature", label: "Nature" },
  { id: "symbols", label: "Symbols" },
];

// Curated set of commonly-used emojis. Quality + reasonable coverage.
// Skin-tone variants and country flags are intentionally omitted.
export const EMOJIS: EmojiEntry[] = [
  // ---------- Smileys ----------
  { char: "😀", name: "grinning", keywords: ["happy", "smile", "grin"], category: "smileys" },
  { char: "😃", name: "smile", keywords: ["happy", "joy", "smile"], category: "smileys" },
  { char: "😄", name: "big smile", keywords: ["happy", "grin", "joy"], category: "smileys" },
  { char: "😁", name: "beaming", keywords: ["smile", "grin", "happy"], category: "smileys" },
  { char: "😆", name: "laughing", keywords: ["laugh", "happy", "haha"], category: "smileys" },
  { char: "😅", name: "sweat smile", keywords: ["nervous", "phew", "relief", "awkward"], category: "smileys" },
  { char: "🤣", name: "rofl", keywords: ["laughing", "rolling", "lol"], category: "smileys" },
  { char: "😂", name: "tears of joy", keywords: ["laugh", "cry", "happy"], category: "smileys" },
  { char: "🙂", name: "slight smile", keywords: ["smile", "ok", "fine"], category: "smileys" },
  { char: "🙃", name: "upside down", keywords: ["sarcastic", "joke", "irony", "fine"], category: "smileys" },
  { char: "🫠", name: "melting", keywords: ["overwhelmed", "tired", "ugh"], category: "smileys" },
  { char: "😉", name: "winking", keywords: ["wink", "flirt", "playful"], category: "smileys" },
  { char: "😊", name: "smiling eyes", keywords: ["happy", "blush", "sweet"], category: "smileys" },
  { char: "😇", name: "halo", keywords: ["angel", "innocent", "good"], category: "smileys" },
  { char: "🥰", name: "loving", keywords: ["love", "hearts", "adore"], category: "smileys" },
  { char: "😍", name: "heart eyes", keywords: ["love", "crush", "adore"], category: "smileys" },
  { char: "🤩", name: "star eyes", keywords: ["wow", "excited", "starstruck"], category: "smileys" },
  { char: "😘", name: "kiss", keywords: ["kiss", "love", "blow"], category: "smileys" },
  { char: "😗", name: "kissing", keywords: ["kiss", "whistle"], category: "smileys" },
  { char: "🥲", name: "smiling tear", keywords: ["proud", "touched", "bittersweet"], category: "smileys" },
  { char: "🥹", name: "holding back tears", keywords: ["proud", "touched", "moved"], category: "smileys" },
  { char: "😋", name: "yum", keywords: ["yum", "tasty", "delicious"], category: "smileys" },
  { char: "😛", name: "tongue out", keywords: ["tongue", "playful"], category: "smileys" },
  { char: "😜", name: "winky tongue", keywords: ["tongue", "wink", "joking"], category: "smileys" },
  { char: "🤪", name: "zany", keywords: ["silly", "wild", "crazy"], category: "smileys" },
  { char: "😝", name: "squinting tongue", keywords: ["tongue", "yuck", "playful"], category: "smileys" },
  { char: "🤑", name: "money mouth", keywords: ["money", "rich", "dollar"], category: "smileys" },
  { char: "🤗", name: "hugs", keywords: ["hug", "embrace", "warm"], category: "smileys" },
  { char: "🫢", name: "open mouth", keywords: ["surprise", "gasp"], category: "smileys" },
  { char: "🫣", name: "peeking", keywords: ["shy", "peek", "nervous"], category: "smileys" },
  { char: "🤭", name: "shushing giggle", keywords: ["oops", "laugh", "shy"], category: "smileys" },
  { char: "🫡", name: "salute", keywords: ["respect", "yes sir", "okay"], category: "smileys" },
  { char: "🤔", name: "thinking", keywords: ["think", "hmm", "ponder"], category: "smileys" },
  { char: "🫥", name: "dotted line face", keywords: ["invisible", "fade", "disappear"], category: "smileys" },
  { char: "🤐", name: "zipped", keywords: ["secret", "quiet", "shut"], category: "smileys" },
  { char: "🤨", name: "raised eyebrow", keywords: ["suspicious", "doubt", "really"], category: "smileys" },
  { char: "😐", name: "neutral", keywords: ["meh", "blank", "okay"], category: "smileys" },
  { char: "😑", name: "expressionless", keywords: ["meh", "blank", "done"], category: "smileys" },
  { char: "😶", name: "no mouth", keywords: ["silent", "speechless"], category: "smileys" },
  { char: "🫤", name: "diagonal mouth", keywords: ["meh", "unsure", "skeptical"], category: "smileys" },
  { char: "😏", name: "smirk", keywords: ["smug", "smirk", "tease"], category: "smileys" },
  { char: "😒", name: "unamused", keywords: ["meh", "annoyed", "side eye"], category: "smileys" },
  { char: "🙄", name: "eye roll", keywords: ["annoyed", "whatever"], category: "smileys" },
  { char: "😬", name: "grimace", keywords: ["awkward", "yikes"], category: "smileys" },
  { char: "😮‍💨", name: "exhaling", keywords: ["sigh", "relief", "tired"], category: "smileys" },
  { char: "🤥", name: "lying", keywords: ["lie", "pinocchio", "dishonest"], category: "smileys" },
  { char: "😌", name: "relieved", keywords: ["calm", "relief", "content"], category: "smileys" },
  { char: "😔", name: "pensive", keywords: ["sad", "thoughtful", "down"], category: "smileys" },
  { char: "😪", name: "sleepy", keywords: ["tired", "drowsy", "yawn"], category: "smileys" },
  { char: "🤤", name: "drool", keywords: ["yum", "drool", "tasty"], category: "smileys" },
  { char: "😴", name: "sleeping", keywords: ["sleep", "tired", "zzz"], category: "smileys" },
  { char: "😷", name: "mask", keywords: ["sick", "mask", "covid"], category: "smileys" },
  { char: "🤒", name: "thermometer", keywords: ["sick", "fever", "ill"], category: "smileys" },
  { char: "🤕", name: "head bandage", keywords: ["hurt", "injured", "ouch"], category: "smileys" },
  { char: "🤧", name: "sneeze", keywords: ["cold", "tissue", "sick"], category: "smileys" },
  { char: "🥵", name: "hot face", keywords: ["hot", "sweat", "warm"], category: "smileys" },
  { char: "🥶", name: "cold face", keywords: ["cold", "freezing", "chill"], category: "smileys" },
  { char: "😵", name: "dizzy", keywords: ["spinning", "knockout", "dazed"], category: "smileys" },
  { char: "😵‍💫", name: "spiral eyes", keywords: ["dizzy", "confused", "lost"], category: "smileys" },
  { char: "🤯", name: "mind blown", keywords: ["shocked", "wow", "exploding"], category: "smileys" },
  { char: "🤠", name: "cowboy", keywords: ["cowboy", "yeehaw", "hat"], category: "smileys" },
  { char: "🥳", name: "party", keywords: ["celebrate", "party", "birthday"], category: "smileys" },
  { char: "🥸", name: "disguise", keywords: ["incognito", "fake", "mustache"], category: "smileys" },
  { char: "😎", name: "cool", keywords: ["cool", "sunglasses", "chill"], category: "smileys" },
  { char: "🤓", name: "nerd", keywords: ["nerd", "smart", "study"], category: "smileys" },
  { char: "🧐", name: "monocle", keywords: ["scrutinize", "fancy", "inspect"], category: "smileys" },
  { char: "😕", name: "confused", keywords: ["confused", "unsure"], category: "smileys" },
  { char: "🥺", name: "pleading", keywords: ["please", "puppy eyes", "begging"], category: "smileys" },
  { char: "😟", name: "worried", keywords: ["worried", "concerned"], category: "smileys" },
  { char: "🙁", name: "slight frown", keywords: ["sad", "unhappy"], category: "smileys" },
  { char: "☹️", name: "frown", keywords: ["sad", "unhappy"], category: "smileys" },
  { char: "😣", name: "persevere", keywords: ["struggle", "effort"], category: "smileys" },
  { char: "😖", name: "confounded", keywords: ["frustrated"], category: "smileys" },
  { char: "😫", name: "tired", keywords: ["tired", "exhausted"], category: "smileys" },
  { char: "😩", name: "weary", keywords: ["weary", "tired"], category: "smileys" },
  { char: "🥱", name: "yawn", keywords: ["yawn", "bored", "tired"], category: "smileys" },
  { char: "😤", name: "huffing", keywords: ["frustrated", "snort", "mad"], category: "smileys" },
  { char: "😡", name: "angry", keywords: ["mad", "rage", "anger"], category: "smileys" },
  { char: "🤬", name: "swearing", keywords: ["cursing", "rage", "angry"], category: "smileys" },
  { char: "🥴", name: "woozy", keywords: ["dizzy", "drunk", "tipsy"], category: "smileys" },
  { char: "😱", name: "scream", keywords: ["scared", "shock", "horror"], category: "smileys" },
  { char: "😨", name: "fearful", keywords: ["scared", "afraid"], category: "smileys" },
  { char: "😰", name: "anxious", keywords: ["worried", "anxious", "stress"], category: "smileys" },
  { char: "😥", name: "sad relief", keywords: ["sad", "relieved"], category: "smileys" },
  { char: "😓", name: "downcast sweat", keywords: ["sweat", "stressed"], category: "smileys" },
  { char: "🤥", name: "liar", keywords: ["lie"], category: "smileys" },
  { char: "🤢", name: "nauseated", keywords: ["sick", "gross"], category: "smileys" },
  { char: "🤮", name: "vomit", keywords: ["sick", "throwup"], category: "smileys" },
  { char: "😭", name: "loudly crying", keywords: ["cry", "sad", "tears"], category: "smileys" },
  { char: "😢", name: "crying", keywords: ["cry", "sad", "tear"], category: "smileys" },
  { char: "😞", name: "disappointed", keywords: ["sad", "down"], category: "smileys" },
  { char: "🤡", name: "clown", keywords: ["clown", "fool"], category: "smileys" },
  { char: "💀", name: "skull", keywords: ["dead", "skull", "rip"], category: "smileys" },
  { char: "☠️", name: "skull crossbones", keywords: ["danger", "death"], category: "smileys" },
  { char: "👻", name: "ghost", keywords: ["spooky", "ghost", "boo"], category: "smileys" },
  { char: "👽", name: "alien", keywords: ["alien", "space"], category: "smileys" },
  { char: "👾", name: "space invader", keywords: ["alien", "game"], category: "smileys" },
  { char: "🤖", name: "robot", keywords: ["robot", "ai", "bot"], category: "smileys" },
  { char: "💩", name: "poop", keywords: ["poop", "crap"], category: "smileys" },
  { char: "😈", name: "devil", keywords: ["evil", "horns", "naughty"], category: "smileys" },
  { char: "👿", name: "imp", keywords: ["devil", "evil"], category: "smileys" },
  { char: "👹", name: "ogre", keywords: ["monster", "demon"], category: "smileys" },
  { char: "🎃", name: "pumpkin", keywords: ["halloween", "jack"], category: "smileys" },

  // ---------- People (hands and gestures) ----------
  { char: "👋", name: "wave", keywords: ["hi", "bye", "hello"], category: "people" },
  { char: "🤚", name: "raised back", keywords: ["stop", "high five"], category: "people" },
  { char: "✋", name: "high five", keywords: ["stop", "high five", "hand"], category: "people" },
  { char: "🖐️", name: "spread hand", keywords: ["five", "stop"], category: "people" },
  { char: "🖖", name: "vulcan", keywords: ["spock", "live long", "trek"], category: "people" },
  { char: "👌", name: "ok", keywords: ["fine", "perfect", "nice"], category: "people" },
  { char: "🤌", name: "pinched fingers", keywords: ["italian", "what", "gesture"], category: "people" },
  { char: "🤏", name: "small", keywords: ["tiny", "pinch", "little"], category: "people" },
  { char: "✌️", name: "peace", keywords: ["peace", "victory", "two"], category: "people" },
  { char: "🤞", name: "fingers crossed", keywords: ["luck", "hope"], category: "people" },
  { char: "🫰", name: "finger heart", keywords: ["money", "kpop", "love"], category: "people" },
  { char: "🤟", name: "love you", keywords: ["asl", "love"], category: "people" },
  { char: "🤘", name: "rock on", keywords: ["rock", "metal", "horns"], category: "people" },
  { char: "🤙", name: "call me", keywords: ["shaka", "hang loose"], category: "people" },
  { char: "🫵", name: "pointing at you", keywords: ["you", "point"], category: "people" },
  { char: "👈", name: "point left", keywords: ["left", "point"], category: "people" },
  { char: "👉", name: "point right", keywords: ["right", "point"], category: "people" },
  { char: "👆", name: "point up", keywords: ["up", "point"], category: "people" },
  { char: "👇", name: "point down", keywords: ["down", "point"], category: "people" },
  { char: "☝️", name: "index up", keywords: ["one", "point", "wait"], category: "people" },
  { char: "👍", name: "thumbs up", keywords: ["yes", "ok", "good", "approve", "like"], category: "people" },
  { char: "👎", name: "thumbs down", keywords: ["no", "bad", "disapprove", "dislike"], category: "people" },
  { char: "✊", name: "fist", keywords: ["solidarity", "fist"], category: "people" },
  { char: "👊", name: "punch", keywords: ["fist bump", "punch"], category: "people" },
  { char: "🫳", name: "palm down", keywords: ["pat", "calm"], category: "people" },
  { char: "🫴", name: "palm up", keywords: ["offer", "give"], category: "people" },
  { char: "👏", name: "clap", keywords: ["applause", "clap", "good job"], category: "people" },
  { char: "🙌", name: "raised hands", keywords: ["yay", "celebration", "praise"], category: "people" },
  { char: "🫶", name: "heart hands", keywords: ["love", "appreciation"], category: "people" },
  { char: "👐", name: "open hands", keywords: ["open", "hug"], category: "people" },
  { char: "🤲", name: "cupped hands", keywords: ["pray", "offer"], category: "people" },
  { char: "🤝", name: "handshake", keywords: ["deal", "agreement", "shake"], category: "people" },
  { char: "🙏", name: "pray", keywords: ["please", "thanks", "prayer"], category: "people" },
  { char: "💪", name: "muscle", keywords: ["strong", "flex", "power"], category: "people" },
  { char: "🦾", name: "mechanical arm", keywords: ["strong", "robot", "arm"], category: "people" },
  { char: "🦵", name: "leg", keywords: ["leg", "kick"], category: "people" },
  { char: "🧠", name: "brain", keywords: ["smart", "think", "mind"], category: "people" },
  { char: "🫀", name: "anatomical heart", keywords: ["heart", "organ"], category: "people" },
  { char: "🫁", name: "lungs", keywords: ["lungs", "breath"], category: "people" },
  { char: "👀", name: "eyes", keywords: ["look", "watching", "see"], category: "people" },
  { char: "👁️", name: "eye", keywords: ["see", "look"], category: "people" },
  { char: "👃", name: "nose", keywords: ["smell"], category: "people" },
  { char: "👂", name: "ear", keywords: ["hear", "listen"], category: "people" },
  { char: "👄", name: "mouth", keywords: ["mouth", "lips"], category: "people" },
  { char: "👶", name: "baby", keywords: ["infant", "baby"], category: "people" },
  { char: "🧒", name: "child", keywords: ["child", "kid"], category: "people" },
  { char: "🧑", name: "person", keywords: ["person", "human"], category: "people" },
  { char: "👨", name: "man", keywords: ["man"], category: "people" },
  { char: "👩", name: "woman", keywords: ["woman"], category: "people" },
  { char: "🧓", name: "older", keywords: ["older", "elderly"], category: "people" },
  { char: "🤵", name: "tuxedo", keywords: ["wedding", "formal"], category: "people" },
  { char: "👰", name: "veil", keywords: ["bride", "wedding"], category: "people" },
  { char: "🤱", name: "breastfeeding", keywords: ["nursing", "baby"], category: "people" },
  { char: "🙇", name: "bowing", keywords: ["sorry", "respect", "bow"], category: "people" },
  { char: "🤦", name: "facepalm", keywords: ["facepalm", "ugh"], category: "people" },
  { char: "🤷", name: "shrug", keywords: ["dunno", "idk"], category: "people" },
  { char: "🙅", name: "no gesture", keywords: ["no", "nope", "deny"], category: "people" },
  { char: "🙆", name: "ok gesture", keywords: ["yes", "ok"], category: "people" },
  { char: "🙋", name: "raised hand", keywords: ["question", "raise hand"], category: "people" },
  { char: "🙎", name: "pouting", keywords: ["pout", "upset"], category: "people" },
  { char: "🙍", name: "frowning", keywords: ["frown", "sad"], category: "people" },
  { char: "💁", name: "info desk", keywords: ["info", "tip"], category: "people" },
  { char: "🚶", name: "walking", keywords: ["walk", "stroll"], category: "people" },
  { char: "🏃", name: "running", keywords: ["run", "jog"], category: "people" },
  { char: "💃", name: "dancer", keywords: ["dance", "party"], category: "people" },
  { char: "🕺", name: "man dancing", keywords: ["dance"], category: "people" },
  { char: "🧘", name: "meditate", keywords: ["yoga", "calm", "zen"], category: "people" },

  // ---------- Love ----------
  { char: "❤️", name: "red heart", keywords: ["love", "red", "heart"], category: "love" },
  { char: "🩷", name: "pink heart", keywords: ["love", "pink"], category: "love" },
  { char: "🧡", name: "orange heart", keywords: ["love", "orange"], category: "love" },
  { char: "💛", name: "yellow heart", keywords: ["love", "yellow", "friendship"], category: "love" },
  { char: "💚", name: "green heart", keywords: ["love", "green", "envy"], category: "love" },
  { char: "💙", name: "blue heart", keywords: ["love", "blue"], category: "love" },
  { char: "🩵", name: "light blue heart", keywords: ["love", "blue"], category: "love" },
  { char: "💜", name: "purple heart", keywords: ["love", "purple"], category: "love" },
  { char: "🤎", name: "brown heart", keywords: ["love", "brown"], category: "love" },
  { char: "🖤", name: "black heart", keywords: ["love", "black"], category: "love" },
  { char: "🩶", name: "grey heart", keywords: ["love", "grey"], category: "love" },
  { char: "🤍", name: "white heart", keywords: ["love", "white"], category: "love" },
  { char: "💔", name: "broken heart", keywords: ["sad", "breakup", "heartbreak"], category: "love" },
  { char: "❤️‍🔥", name: "heart on fire", keywords: ["passion", "love", "lust"], category: "love" },
  { char: "❤️‍🩹", name: "mending heart", keywords: ["healing", "recovery"], category: "love" },
  { char: "❣️", name: "heart exclamation", keywords: ["love", "emphasis"], category: "love" },
  { char: "💕", name: "two hearts", keywords: ["love", "hearts"], category: "love" },
  { char: "💞", name: "revolving hearts", keywords: ["love", "spinning"], category: "love" },
  { char: "💓", name: "beating heart", keywords: ["love", "pulse"], category: "love" },
  { char: "💗", name: "growing heart", keywords: ["love", "growing"], category: "love" },
  { char: "💖", name: "sparkle heart", keywords: ["love", "sparkle"], category: "love" },
  { char: "💘", name: "heart arrow", keywords: ["love", "cupid", "arrow"], category: "love" },
  { char: "💝", name: "heart gift", keywords: ["love", "gift", "ribbon"], category: "love" },
  { char: "💟", name: "heart decoration", keywords: ["love"], category: "love" },
  { char: "💌", name: "love letter", keywords: ["love", "letter", "note"], category: "love" },
  { char: "💋", name: "kiss mark", keywords: ["kiss", "lipstick"], category: "love" },
  { char: "♥️", name: "heart suit", keywords: ["card", "love"], category: "love" },

  // ---------- Animals ----------
  { char: "🐶", name: "dog", keywords: ["dog", "puppy", "pet"], category: "animals" },
  { char: "🐱", name: "cat", keywords: ["cat", "kitten", "pet"], category: "animals" },
  { char: "🐭", name: "mouse", keywords: ["mouse", "small"], category: "animals" },
  { char: "🐹", name: "hamster", keywords: ["hamster", "pet"], category: "animals" },
  { char: "🐰", name: "rabbit", keywords: ["bunny", "rabbit"], category: "animals" },
  { char: "🦊", name: "fox", keywords: ["fox"], category: "animals" },
  { char: "🐻", name: "bear", keywords: ["bear"], category: "animals" },
  { char: "🐼", name: "panda", keywords: ["panda"], category: "animals" },
  { char: "🐨", name: "koala", keywords: ["koala"], category: "animals" },
  { char: "🦁", name: "lion", keywords: ["lion"], category: "animals" },
  { char: "🐯", name: "tiger", keywords: ["tiger"], category: "animals" },
  { char: "🦒", name: "giraffe", keywords: ["giraffe"], category: "animals" },
  { char: "🐮", name: "cow", keywords: ["cow"], category: "animals" },
  { char: "🐷", name: "pig", keywords: ["pig"], category: "animals" },
  { char: "🐸", name: "frog", keywords: ["frog"], category: "animals" },
  { char: "🐵", name: "monkey face", keywords: ["monkey"], category: "animals" },
  { char: "🐒", name: "monkey", keywords: ["monkey"], category: "animals" },
  { char: "🦝", name: "raccoon", keywords: ["raccoon"], category: "animals" },
  { char: "🐔", name: "chicken", keywords: ["chicken", "bird"], category: "animals" },
  { char: "🐓", name: "rooster", keywords: ["rooster"], category: "animals" },
  { char: "🦆", name: "duck", keywords: ["duck"], category: "animals" },
  { char: "🦢", name: "swan", keywords: ["swan"], category: "animals" },
  { char: "🦉", name: "owl", keywords: ["owl", "wise"], category: "animals" },
  { char: "🦅", name: "eagle", keywords: ["eagle"], category: "animals" },
  { char: "🐧", name: "penguin", keywords: ["penguin", "bird"], category: "animals" },
  { char: "🦩", name: "flamingo", keywords: ["flamingo", "pink"], category: "animals" },
  { char: "🦚", name: "peacock", keywords: ["peacock"], category: "animals" },
  { char: "🦜", name: "parrot", keywords: ["parrot"], category: "animals" },
  { char: "🐦", name: "bird", keywords: ["bird"], category: "animals" },
  { char: "🐤", name: "chick", keywords: ["chick"], category: "animals" },
  { char: "🦄", name: "unicorn", keywords: ["unicorn", "magic"], category: "animals" },
  { char: "🐎", name: "horse", keywords: ["horse"], category: "animals" },
  { char: "🦓", name: "zebra", keywords: ["zebra"], category: "animals" },
  { char: "🦘", name: "kangaroo", keywords: ["kangaroo"], category: "animals" },
  { char: "🐘", name: "elephant", keywords: ["elephant"], category: "animals" },
  { char: "🦏", name: "rhino", keywords: ["rhino"], category: "animals" },
  { char: "🦛", name: "hippo", keywords: ["hippo"], category: "animals" },
  { char: "🐺", name: "wolf", keywords: ["wolf"], category: "animals" },
  { char: "🐗", name: "boar", keywords: ["pig", "boar"], category: "animals" },
  { char: "🐝", name: "bee", keywords: ["bee", "busy"], category: "animals" },
  { char: "🦋", name: "butterfly", keywords: ["butterfly"], category: "animals" },
  { char: "🐛", name: "caterpillar", keywords: ["bug", "caterpillar"], category: "animals" },
  { char: "🐌", name: "snail", keywords: ["snail", "slow"], category: "animals" },
  { char: "🐞", name: "ladybug", keywords: ["bug", "ladybug"], category: "animals" },
  { char: "🐜", name: "ant", keywords: ["ant"], category: "animals" },
  { char: "🕷️", name: "spider", keywords: ["spider"], category: "animals" },
  { char: "🦂", name: "scorpion", keywords: ["scorpion"], category: "animals" },
  { char: "🐢", name: "turtle", keywords: ["turtle", "slow"], category: "animals" },
  { char: "🐍", name: "snake", keywords: ["snake"], category: "animals" },
  { char: "🦎", name: "lizard", keywords: ["lizard"], category: "animals" },
  { char: "🐊", name: "crocodile", keywords: ["crocodile", "alligator"], category: "animals" },
  { char: "🐉", name: "dragon", keywords: ["dragon"], category: "animals" },
  { char: "🦕", name: "sauropod", keywords: ["dinosaur"], category: "animals" },
  { char: "🦖", name: "t-rex", keywords: ["dinosaur", "trex"], category: "animals" },
  { char: "🐳", name: "whale", keywords: ["whale", "ocean"], category: "animals" },
  { char: "🐬", name: "dolphin", keywords: ["dolphin"], category: "animals" },
  { char: "🦈", name: "shark", keywords: ["shark"], category: "animals" },
  { char: "🐟", name: "fish", keywords: ["fish"], category: "animals" },
  { char: "🐠", name: "tropical fish", keywords: ["fish", "tropical"], category: "animals" },
  { char: "🐡", name: "blowfish", keywords: ["fish"], category: "animals" },
  { char: "🐙", name: "octopus", keywords: ["octopus"], category: "animals" },
  { char: "🦀", name: "crab", keywords: ["crab"], category: "animals" },
  { char: "🦞", name: "lobster", keywords: ["lobster"], category: "animals" },
  { char: "🦐", name: "shrimp", keywords: ["shrimp"], category: "animals" },
  { char: "🐚", name: "shell", keywords: ["shell", "ocean"], category: "animals" },
  { char: "🐾", name: "paw prints", keywords: ["paws", "tracks"], category: "animals" },

  // ---------- Food ----------
  { char: "🍎", name: "apple", keywords: ["apple", "fruit"], category: "food" },
  { char: "🍏", name: "green apple", keywords: ["apple", "fruit", "green"], category: "food" },
  { char: "🍐", name: "pear", keywords: ["pear", "fruit"], category: "food" },
  { char: "🍊", name: "tangerine", keywords: ["orange", "fruit"], category: "food" },
  { char: "🍋", name: "lemon", keywords: ["lemon", "citrus"], category: "food" },
  { char: "🍌", name: "banana", keywords: ["banana", "fruit"], category: "food" },
  { char: "🍉", name: "watermelon", keywords: ["watermelon", "fruit"], category: "food" },
  { char: "🍇", name: "grapes", keywords: ["grapes", "fruit"], category: "food" },
  { char: "🍓", name: "strawberry", keywords: ["strawberry", "fruit"], category: "food" },
  { char: "🫐", name: "blueberries", keywords: ["berry", "fruit"], category: "food" },
  { char: "🍒", name: "cherries", keywords: ["cherry", "fruit"], category: "food" },
  { char: "🍑", name: "peach", keywords: ["peach", "fruit"], category: "food" },
  { char: "🥭", name: "mango", keywords: ["mango", "fruit"], category: "food" },
  { char: "🍍", name: "pineapple", keywords: ["pineapple", "fruit"], category: "food" },
  { char: "🥥", name: "coconut", keywords: ["coconut"], category: "food" },
  { char: "🥝", name: "kiwi", keywords: ["kiwi", "fruit"], category: "food" },
  { char: "🍅", name: "tomato", keywords: ["tomato"], category: "food" },
  { char: "🍆", name: "eggplant", keywords: ["eggplant", "aubergine"], category: "food" },
  { char: "🥑", name: "avocado", keywords: ["avocado"], category: "food" },
  { char: "🥕", name: "carrot", keywords: ["carrot", "vegetable"], category: "food" },
  { char: "🌽", name: "corn", keywords: ["corn"], category: "food" },
  { char: "🌶️", name: "chili", keywords: ["chili", "pepper", "spicy"], category: "food" },
  { char: "🥒", name: "cucumber", keywords: ["cucumber", "pickle"], category: "food" },
  { char: "🥦", name: "broccoli", keywords: ["broccoli"], category: "food" },
  { char: "🥬", name: "leafy green", keywords: ["lettuce", "salad"], category: "food" },
  { char: "🧄", name: "garlic", keywords: ["garlic"], category: "food" },
  { char: "🧅", name: "onion", keywords: ["onion"], category: "food" },
  { char: "🥔", name: "potato", keywords: ["potato"], category: "food" },
  { char: "🍠", name: "sweet potato", keywords: ["potato", "yam"], category: "food" },
  { char: "🥜", name: "peanuts", keywords: ["peanut", "nuts"], category: "food" },
  { char: "🌰", name: "chestnut", keywords: ["nut", "chestnut"], category: "food" },
  { char: "🍞", name: "bread", keywords: ["bread", "loaf"], category: "food" },
  { char: "🥖", name: "baguette", keywords: ["bread", "french"], category: "food" },
  { char: "🥐", name: "croissant", keywords: ["croissant", "bread"], category: "food" },
  { char: "🥨", name: "pretzel", keywords: ["pretzel"], category: "food" },
  { char: "🥯", name: "bagel", keywords: ["bagel"], category: "food" },
  { char: "🧀", name: "cheese", keywords: ["cheese"], category: "food" },
  { char: "🥚", name: "egg", keywords: ["egg"], category: "food" },
  { char: "🍳", name: "fried egg", keywords: ["egg", "fried", "breakfast"], category: "food" },
  { char: "🥞", name: "pancakes", keywords: ["pancakes", "breakfast"], category: "food" },
  { char: "🧇", name: "waffle", keywords: ["waffle", "breakfast"], category: "food" },
  { char: "🥓", name: "bacon", keywords: ["bacon"], category: "food" },
  { char: "🍔", name: "burger", keywords: ["burger", "hamburger"], category: "food" },
  { char: "🍟", name: "fries", keywords: ["fries", "chips"], category: "food" },
  { char: "🍕", name: "pizza", keywords: ["pizza"], category: "food" },
  { char: "🌭", name: "hot dog", keywords: ["hotdog", "sausage"], category: "food" },
  { char: "🥪", name: "sandwich", keywords: ["sandwich"], category: "food" },
  { char: "🌮", name: "taco", keywords: ["taco", "mexican"], category: "food" },
  { char: "🌯", name: "burrito", keywords: ["burrito", "wrap"], category: "food" },
  { char: "🥗", name: "salad", keywords: ["salad", "healthy"], category: "food" },
  { char: "🍝", name: "pasta", keywords: ["pasta", "spaghetti"], category: "food" },
  { char: "🍜", name: "ramen", keywords: ["ramen", "noodles"], category: "food" },
  { char: "🥘", name: "shallow pan", keywords: ["paella", "pan"], category: "food" },
  { char: "🍲", name: "pot of food", keywords: ["stew", "soup"], category: "food" },
  { char: "🥟", name: "dumpling", keywords: ["dumpling", "gyoza"], category: "food" },
  { char: "🍣", name: "sushi", keywords: ["sushi", "japanese"], category: "food" },
  { char: "🍤", name: "shrimp tempura", keywords: ["shrimp", "tempura"], category: "food" },
  { char: "🍱", name: "bento", keywords: ["bento", "lunch"], category: "food" },
  { char: "🍙", name: "rice ball", keywords: ["onigiri", "rice"], category: "food" },
  { char: "🍚", name: "rice", keywords: ["rice"], category: "food" },
  { char: "🍢", name: "oden", keywords: ["skewer"], category: "food" },
  { char: "🍩", name: "donut", keywords: ["donut", "doughnut"], category: "food" },
  { char: "🍪", name: "cookie", keywords: ["cookie", "biscuit"], category: "food" },
  { char: "🎂", name: "birthday cake", keywords: ["cake", "birthday"], category: "food" },
  { char: "🍰", name: "cake", keywords: ["cake", "dessert"], category: "food" },
  { char: "🧁", name: "cupcake", keywords: ["cupcake"], category: "food" },
  { char: "🥧", name: "pie", keywords: ["pie"], category: "food" },
  { char: "🍫", name: "chocolate", keywords: ["chocolate"], category: "food" },
  { char: "🍬", name: "candy", keywords: ["candy"], category: "food" },
  { char: "🍭", name: "lollipop", keywords: ["lollipop"], category: "food" },
  { char: "🍮", name: "custard", keywords: ["custard", "flan"], category: "food" },
  { char: "🍯", name: "honey", keywords: ["honey"], category: "food" },
  { char: "🍦", name: "soft serve", keywords: ["ice cream"], category: "food" },
  { char: "🍨", name: "ice cream", keywords: ["ice cream"], category: "food" },
  { char: "🍿", name: "popcorn", keywords: ["popcorn", "movie"], category: "food" },
  { char: "🥛", name: "milk", keywords: ["milk", "drink"], category: "food" },
  { char: "☕️", name: "coffee", keywords: ["coffee", "drink"], category: "food" },
  { char: "🍵", name: "tea", keywords: ["tea", "drink"], category: "food" },
  { char: "🫖", name: "teapot", keywords: ["tea"], category: "food" },
  { char: "🧋", name: "boba", keywords: ["bubble tea", "boba"], category: "food" },
  { char: "🥤", name: "cup with straw", keywords: ["soda", "drink"], category: "food" },
  { char: "🧃", name: "juice box", keywords: ["juice"], category: "food" },
  { char: "🫗", name: "pouring", keywords: ["pour", "drink"], category: "food" },
  { char: "🍷", name: "wine", keywords: ["wine"], category: "food" },
  { char: "🍺", name: "beer", keywords: ["beer"], category: "food" },
  { char: "🍻", name: "cheers", keywords: ["beers", "cheers", "toast"], category: "food" },
  { char: "🥂", name: "champagne toast", keywords: ["clink", "toast", "celebrate"], category: "food" },
  { char: "🥃", name: "tumbler", keywords: ["whiskey", "drink"], category: "food" },
  { char: "🍹", name: "tropical drink", keywords: ["cocktail", "vacation"], category: "food" },
  { char: "🍸", name: "cocktail", keywords: ["cocktail", "martini"], category: "food" },
  { char: "🥢", name: "chopsticks", keywords: ["chopsticks", "asian"], category: "food" },
  { char: "🍽️", name: "plate", keywords: ["plate", "dinner"], category: "food" },

  // ---------- Travel ----------
  { char: "🚗", name: "car", keywords: ["car", "drive"], category: "travel" },
  { char: "🚕", name: "taxi", keywords: ["taxi", "cab"], category: "travel" },
  { char: "🚙", name: "suv", keywords: ["car", "suv"], category: "travel" },
  { char: "🚌", name: "bus", keywords: ["bus"], category: "travel" },
  { char: "🚎", name: "trolleybus", keywords: ["bus"], category: "travel" },
  { char: "🚐", name: "minibus", keywords: ["van"], category: "travel" },
  { char: "🚓", name: "police car", keywords: ["police"], category: "travel" },
  { char: "🚑", name: "ambulance", keywords: ["ambulance", "ems"], category: "travel" },
  { char: "🚒", name: "fire truck", keywords: ["firetruck"], category: "travel" },
  { char: "🚚", name: "truck", keywords: ["truck", "delivery"], category: "travel" },
  { char: "🚜", name: "tractor", keywords: ["tractor", "farm"], category: "travel" },
  { char: "🏎️", name: "race car", keywords: ["car", "racing"], category: "travel" },
  { char: "🏍️", name: "motorcycle", keywords: ["bike", "motorcycle"], category: "travel" },
  { char: "🛵", name: "scooter", keywords: ["vespa", "scooter"], category: "travel" },
  { char: "🛺", name: "auto rickshaw", keywords: ["tuktuk"], category: "travel" },
  { char: "🚲", name: "bike", keywords: ["bike", "bicycle"], category: "travel" },
  { char: "🛴", name: "kick scooter", keywords: ["scooter"], category: "travel" },
  { char: "🛹", name: "skateboard", keywords: ["skate"], category: "travel" },
  { char: "🛼", name: "rollerskate", keywords: ["skate"], category: "travel" },
  { char: "🚂", name: "train", keywords: ["train", "steam"], category: "travel" },
  { char: "🚆", name: "train", keywords: ["train"], category: "travel" },
  { char: "🚇", name: "metro", keywords: ["subway", "metro"], category: "travel" },
  { char: "🚊", name: "tram", keywords: ["tram"], category: "travel" },
  { char: "🚉", name: "station", keywords: ["station"], category: "travel" },
  { char: "🚀", name: "rocket", keywords: ["rocket", "launch", "space"], category: "travel" },
  { char: "🛸", name: "ufo", keywords: ["ufo", "saucer"], category: "travel" },
  { char: "✈️", name: "plane", keywords: ["plane", "airplane", "travel"], category: "travel" },
  { char: "🛫", name: "departure", keywords: ["takeoff"], category: "travel" },
  { char: "🛬", name: "arrival", keywords: ["land"], category: "travel" },
  { char: "🚁", name: "helicopter", keywords: ["helicopter"], category: "travel" },
  { char: "⛵️", name: "sailboat", keywords: ["sailboat", "boat"], category: "travel" },
  { char: "🚤", name: "speedboat", keywords: ["boat", "speedboat"], category: "travel" },
  { char: "🚢", name: "ship", keywords: ["ship", "ocean"], category: "travel" },
  { char: "⛴️", name: "ferry", keywords: ["ferry", "boat"], category: "travel" },
  { char: "🛶", name: "canoe", keywords: ["canoe", "kayak"], category: "travel" },
  { char: "🚏", name: "bus stop", keywords: ["stop"], category: "travel" },
  { char: "🚦", name: "traffic light", keywords: ["traffic", "stop"], category: "travel" },
  { char: "⚓️", name: "anchor", keywords: ["anchor"], category: "travel" },
  { char: "⛽️", name: "gas pump", keywords: ["gas", "fuel"], category: "travel" },
  { char: "🏠", name: "house", keywords: ["house", "home"], category: "travel" },
  { char: "🏡", name: "garden house", keywords: ["home", "garden"], category: "travel" },
  { char: "🏢", name: "office", keywords: ["office", "building"], category: "travel" },
  { char: "🏥", name: "hospital", keywords: ["hospital"], category: "travel" },
  { char: "🏦", name: "bank", keywords: ["bank"], category: "travel" },
  { char: "🏨", name: "hotel", keywords: ["hotel"], category: "travel" },
  { char: "🏪", name: "convenience store", keywords: ["store", "shop"], category: "travel" },
  { char: "🏫", name: "school", keywords: ["school"], category: "travel" },
  { char: "🏬", name: "department store", keywords: ["store"], category: "travel" },
  { char: "🏭", name: "factory", keywords: ["factory"], category: "travel" },
  { char: "🏯", name: "castle", keywords: ["castle"], category: "travel" },
  { char: "🏰", name: "european castle", keywords: ["castle"], category: "travel" },
  { char: "🗼", name: "tower", keywords: ["tokyo", "tower"], category: "travel" },
  { char: "🗽", name: "statue of liberty", keywords: ["new york", "usa"], category: "travel" },
  { char: "🌍", name: "earth europe africa", keywords: ["world", "earth"], category: "travel" },
  { char: "🌎", name: "earth americas", keywords: ["world", "earth"], category: "travel" },
  { char: "🌏", name: "earth asia", keywords: ["world", "earth"], category: "travel" },
  { char: "🗺️", name: "world map", keywords: ["map"], category: "travel" },
  { char: "⛰️", name: "mountain", keywords: ["mountain"], category: "travel" },
  { char: "🏔️", name: "snow mountain", keywords: ["mountain", "snow"], category: "travel" },
  { char: "🌋", name: "volcano", keywords: ["volcano"], category: "travel" },
  { char: "🏕️", name: "camping", keywords: ["camping", "tent"], category: "travel" },
  { char: "🏖️", name: "beach", keywords: ["beach", "vacation"], category: "travel" },
  { char: "🏜️", name: "desert", keywords: ["desert"], category: "travel" },
  { char: "🏝️", name: "island", keywords: ["island"], category: "travel" },

  // ---------- Activity ----------
  { char: "⚽️", name: "soccer", keywords: ["soccer", "football"], category: "activity" },
  { char: "🏀", name: "basketball", keywords: ["basketball"], category: "activity" },
  { char: "🏈", name: "american football", keywords: ["football"], category: "activity" },
  { char: "⚾️", name: "baseball", keywords: ["baseball"], category: "activity" },
  { char: "🥎", name: "softball", keywords: ["softball"], category: "activity" },
  { char: "🎾", name: "tennis", keywords: ["tennis"], category: "activity" },
  { char: "🏐", name: "volleyball", keywords: ["volleyball"], category: "activity" },
  { char: "🏉", name: "rugby", keywords: ["rugby"], category: "activity" },
  { char: "🥏", name: "frisbee", keywords: ["frisbee", "disc"], category: "activity" },
  { char: "🎱", name: "8 ball", keywords: ["pool", "billiards"], category: "activity" },
  { char: "🏓", name: "ping pong", keywords: ["table tennis"], category: "activity" },
  { char: "🏸", name: "badminton", keywords: ["badminton"], category: "activity" },
  { char: "🥅", name: "goal", keywords: ["goal", "net"], category: "activity" },
  { char: "🏒", name: "ice hockey", keywords: ["hockey"], category: "activity" },
  { char: "🥊", name: "boxing", keywords: ["boxing", "glove"], category: "activity" },
  { char: "🥋", name: "martial arts", keywords: ["karate", "judo"], category: "activity" },
  { char: "⛳️", name: "golf", keywords: ["golf"], category: "activity" },
  { char: "⛸️", name: "ice skate", keywords: ["skate", "ice"], category: "activity" },
  { char: "🎿", name: "skis", keywords: ["ski", "snow"], category: "activity" },
  { char: "🏂", name: "snowboard", keywords: ["snowboard"], category: "activity" },
  { char: "🏋️", name: "lift", keywords: ["workout", "lifting", "gym"], category: "activity" },
  { char: "🤼", name: "wrestling", keywords: ["wrestling"], category: "activity" },
  { char: "🤸", name: "cartwheel", keywords: ["cartwheel"], category: "activity" },
  { char: "🤽", name: "water polo", keywords: ["water polo"], category: "activity" },
  { char: "🏌️", name: "golfer", keywords: ["golf"], category: "activity" },
  { char: "🏇", name: "horse racing", keywords: ["jockey", "horse"], category: "activity" },
  { char: "🏊", name: "swim", keywords: ["swim"], category: "activity" },
  { char: "🚴", name: "cyclist", keywords: ["bike", "cycling"], category: "activity" },
  { char: "🚵", name: "mountain bike", keywords: ["bike"], category: "activity" },
  { char: "🎯", name: "bullseye", keywords: ["target", "darts"], category: "activity" },
  { char: "🎲", name: "dice", keywords: ["dice", "game"], category: "activity" },
  { char: "🃏", name: "joker", keywords: ["card", "joker"], category: "activity" },
  { char: "♟️", name: "chess pawn", keywords: ["chess"], category: "activity" },
  { char: "🎮", name: "video game", keywords: ["game", "controller"], category: "activity" },
  { char: "🕹️", name: "joystick", keywords: ["arcade", "game"], category: "activity" },
  { char: "🎰", name: "slot machine", keywords: ["gambling", "slots"], category: "activity" },
  { char: "🧩", name: "puzzle piece", keywords: ["puzzle"], category: "activity" },
  { char: "🎨", name: "art", keywords: ["paint", "art"], category: "activity" },
  { char: "🎭", name: "theatre", keywords: ["theatre", "drama"], category: "activity" },
  { char: "🎤", name: "microphone", keywords: ["mic", "sing", "karaoke"], category: "activity" },
  { char: "🎧", name: "headphones", keywords: ["headphones", "music"], category: "activity" },
  { char: "🎵", name: "music note", keywords: ["music", "note"], category: "activity" },
  { char: "🎶", name: "music notes", keywords: ["music", "song"], category: "activity" },
  { char: "🎸", name: "guitar", keywords: ["guitar", "music"], category: "activity" },
  { char: "🎹", name: "piano", keywords: ["piano", "keyboard"], category: "activity" },
  { char: "🥁", name: "drum", keywords: ["drum"], category: "activity" },
  { char: "🎺", name: "trumpet", keywords: ["trumpet"], category: "activity" },
  { char: "🎻", name: "violin", keywords: ["violin"], category: "activity" },
  { char: "🎷", name: "saxophone", keywords: ["sax"], category: "activity" },
  { char: "🎬", name: "clapper", keywords: ["movie", "film"], category: "activity" },
  { char: "📚", name: "books", keywords: ["books", "read", "library"], category: "activity" },
  { char: "🪀", name: "yoyo", keywords: ["yoyo"], category: "activity" },
  { char: "🪁", name: "kite", keywords: ["kite"], category: "activity" },
  { char: "🎪", name: "circus tent", keywords: ["circus"], category: "activity" },

  // ---------- Objects ----------
  { char: "💻", name: "laptop", keywords: ["computer", "laptop", "work"], category: "objects" },
  { char: "🖥️", name: "desktop", keywords: ["computer", "monitor"], category: "objects" },
  { char: "📱", name: "phone", keywords: ["phone", "mobile"], category: "objects" },
  { char: "☎️", name: "old phone", keywords: ["phone", "rotary"], category: "objects" },
  { char: "⌨️", name: "keyboard", keywords: ["keyboard"], category: "objects" },
  { char: "🖱️", name: "mouse device", keywords: ["mouse"], category: "objects" },
  { char: "🖨️", name: "printer", keywords: ["printer"], category: "objects" },
  { char: "💾", name: "floppy disk", keywords: ["save", "disk"], category: "objects" },
  { char: "📷", name: "camera", keywords: ["camera", "photo"], category: "objects" },
  { char: "📸", name: "camera flash", keywords: ["camera", "photo"], category: "objects" },
  { char: "🎥", name: "movie camera", keywords: ["camera", "video"], category: "objects" },
  { char: "📺", name: "tv", keywords: ["tv"], category: "objects" },
  { char: "📻", name: "radio", keywords: ["radio"], category: "objects" },
  { char: "🔋", name: "battery", keywords: ["battery", "power"], category: "objects" },
  { char: "🔌", name: "plug", keywords: ["plug", "power"], category: "objects" },
  { char: "💡", name: "lightbulb", keywords: ["idea", "light"], category: "objects" },
  { char: "🔦", name: "flashlight", keywords: ["torch", "flashlight"], category: "objects" },
  { char: "🕯️", name: "candle", keywords: ["candle"], category: "objects" },
  { char: "🔍", name: "magnifier", keywords: ["search", "find", "look"], category: "objects" },
  { char: "🔎", name: "magnifier right", keywords: ["search"], category: "objects" },
  { char: "🔒", name: "lock", keywords: ["locked", "secure"], category: "objects" },
  { char: "🔓", name: "unlock", keywords: ["unlocked"], category: "objects" },
  { char: "🔑", name: "key", keywords: ["key", "unlock"], category: "objects" },
  { char: "🗝️", name: "old key", keywords: ["key"], category: "objects" },
  { char: "🛡️", name: "shield", keywords: ["shield", "protect"], category: "objects" },
  { char: "🪙", name: "coin", keywords: ["coin", "money"], category: "objects" },
  { char: "💰", name: "money bag", keywords: ["money", "cash"], category: "objects" },
  { char: "💵", name: "dollar bill", keywords: ["money", "cash"], category: "objects" },
  { char: "💳", name: "credit card", keywords: ["card", "payment"], category: "objects" },
  { char: "💸", name: "money fly", keywords: ["money", "spend"], category: "objects" },
  { char: "📦", name: "package", keywords: ["box", "package"], category: "objects" },
  { char: "📫", name: "mailbox", keywords: ["mail"], category: "objects" },
  { char: "📨", name: "envelope arrow", keywords: ["mail", "incoming"], category: "objects" },
  { char: "✉️", name: "envelope", keywords: ["mail", "letter"], category: "objects" },
  { char: "📌", name: "pin", keywords: ["pin", "pushpin"], category: "objects" },
  { char: "📍", name: "round pin", keywords: ["location", "pin"], category: "objects" },
  { char: "📎", name: "paperclip", keywords: ["paperclip"], category: "objects" },
  { char: "📝", name: "memo", keywords: ["note", "write", "memo"], category: "objects" },
  { char: "✏️", name: "pencil", keywords: ["pencil", "write"], category: "objects" },
  { char: "🖊️", name: "pen", keywords: ["pen"], category: "objects" },
  { char: "🖋️", name: "fountain pen", keywords: ["pen"], category: "objects" },
  { char: "🖌️", name: "paintbrush", keywords: ["brush", "paint"], category: "objects" },
  { char: "🖍️", name: "crayon", keywords: ["crayon"], category: "objects" },
  { char: "✂️", name: "scissors", keywords: ["cut", "scissors"], category: "objects" },
  { char: "📐", name: "ruler triangle", keywords: ["ruler"], category: "objects" },
  { char: "📏", name: "ruler", keywords: ["ruler", "measure"], category: "objects" },
  { char: "📅", name: "calendar", keywords: ["calendar", "date"], category: "objects" },
  { char: "📆", name: "tear-off calendar", keywords: ["calendar"], category: "objects" },
  { char: "📊", name: "bar chart", keywords: ["chart", "graph"], category: "objects" },
  { char: "📈", name: "chart up", keywords: ["chart", "up"], category: "objects" },
  { char: "📉", name: "chart down", keywords: ["chart", "down"], category: "objects" },
  { char: "📋", name: "clipboard", keywords: ["clipboard"], category: "objects" },
  { char: "🗂️", name: "card index", keywords: ["files", "tabs"], category: "objects" },
  { char: "📁", name: "folder", keywords: ["folder"], category: "objects" },
  { char: "📂", name: "open folder", keywords: ["folder"], category: "objects" },
  { char: "📒", name: "ledger", keywords: ["notebook"], category: "objects" },
  { char: "📕", name: "closed book", keywords: ["book"], category: "objects" },
  { char: "📖", name: "open book", keywords: ["book", "reading"], category: "objects" },
  { char: "🔖", name: "bookmark", keywords: ["bookmark"], category: "objects" },
  { char: "🏷️", name: "label", keywords: ["tag", "label"], category: "objects" },
  { char: "⏰", name: "alarm", keywords: ["alarm", "clock", "time"], category: "objects" },
  { char: "⏱️", name: "stopwatch", keywords: ["timer"], category: "objects" },
  { char: "⏳", name: "hourglass running", keywords: ["timer"], category: "objects" },
  { char: "⌛", name: "hourglass done", keywords: ["timer"], category: "objects" },
  { char: "🎁", name: "gift", keywords: ["gift", "present"], category: "objects" },
  { char: "🎈", name: "balloon", keywords: ["balloon", "party"], category: "objects" },
  { char: "🎉", name: "party popper", keywords: ["party", "celebrate"], category: "objects" },
  { char: "🎊", name: "confetti ball", keywords: ["party"], category: "objects" },
  { char: "🛒", name: "cart", keywords: ["cart", "shopping"], category: "objects" },
  { char: "🎒", name: "backpack", keywords: ["backpack"], category: "objects" },
  { char: "👜", name: "handbag", keywords: ["bag", "purse"], category: "objects" },
  { char: "🪑", name: "chair", keywords: ["chair"], category: "objects" },
  { char: "🛏️", name: "bed", keywords: ["bed", "sleep"], category: "objects" },
  { char: "🛁", name: "bathtub", keywords: ["bath"], category: "objects" },
  { char: "🚿", name: "shower", keywords: ["shower"], category: "objects" },
  { char: "🚽", name: "toilet", keywords: ["toilet"], category: "objects" },
  { char: "🚪", name: "door", keywords: ["door"], category: "objects" },
  { char: "🪞", name: "mirror", keywords: ["mirror"], category: "objects" },
  { char: "🪟", name: "window", keywords: ["window"], category: "objects" },
  { char: "🧹", name: "broom", keywords: ["sweep", "clean"], category: "objects" },
  { char: "🪥", name: "toothbrush", keywords: ["teeth", "brush"], category: "objects" },
  { char: "🧴", name: "lotion bottle", keywords: ["lotion", "shampoo"], category: "objects" },
  { char: "🪒", name: "razor", keywords: ["razor", "shave"], category: "objects" },
  { char: "🔧", name: "wrench", keywords: ["wrench", "tool"], category: "objects" },
  { char: "🔨", name: "hammer", keywords: ["hammer", "tool"], category: "objects" },
  { char: "🛠️", name: "tools", keywords: ["tools"], category: "objects" },
  { char: "⚙️", name: "gear", keywords: ["settings", "gear"], category: "objects" },
  { char: "🧪", name: "test tube", keywords: ["lab", "science"], category: "objects" },
  { char: "🔬", name: "microscope", keywords: ["microscope", "science"], category: "objects" },
  { char: "🔭", name: "telescope", keywords: ["telescope", "astronomy"], category: "objects" },
  { char: "🩺", name: "stethoscope", keywords: ["doctor"], category: "objects" },
  { char: "💉", name: "syringe", keywords: ["needle", "shot", "vaccine"], category: "objects" },
  { char: "💊", name: "pill", keywords: ["pill", "medicine"], category: "objects" },
  { char: "🧸", name: "teddy bear", keywords: ["toy", "bear"], category: "objects" },

  // ---------- Nature ----------
  { char: "🌞", name: "sun", keywords: ["sun", "sunny"], category: "nature" },
  { char: "🌝", name: "smiling moon", keywords: ["moon"], category: "nature" },
  { char: "🌛", name: "first quarter moon", keywords: ["moon"], category: "nature" },
  { char: "🌜", name: "last quarter moon", keywords: ["moon"], category: "nature" },
  { char: "🌚", name: "new moon face", keywords: ["moon"], category: "nature" },
  { char: "🌑", name: "new moon", keywords: ["moon"], category: "nature" },
  { char: "🌒", name: "waxing crescent", keywords: ["moon"], category: "nature" },
  { char: "🌓", name: "first quarter", keywords: ["moon"], category: "nature" },
  { char: "🌔", name: "waxing gibbous", keywords: ["moon"], category: "nature" },
  { char: "🌕", name: "full moon", keywords: ["moon"], category: "nature" },
  { char: "🌖", name: "waning gibbous", keywords: ["moon"], category: "nature" },
  { char: "🌗", name: "last quarter", keywords: ["moon"], category: "nature" },
  { char: "🌘", name: "waning crescent", keywords: ["moon"], category: "nature" },
  { char: "🌙", name: "moon", keywords: ["moon", "night"], category: "nature" },
  { char: "🌎", name: "earth", keywords: ["earth", "world"], category: "nature" },
  { char: "🌌", name: "milky way", keywords: ["space", "galaxy"], category: "nature" },
  { char: "⭐️", name: "star", keywords: ["star"], category: "nature" },
  { char: "🌟", name: "glowing star", keywords: ["star", "shine"], category: "nature" },
  { char: "💫", name: "shooting star", keywords: ["star"], category: "nature" },
  { char: "✨", name: "sparkles", keywords: ["sparkle", "magic"], category: "nature" },
  { char: "☀️", name: "sunshine", keywords: ["sun"], category: "nature" },
  { char: "🌤️", name: "sun small cloud", keywords: ["sun", "cloud"], category: "nature" },
  { char: "⛅️", name: "sun behind cloud", keywords: ["cloud", "sun"], category: "nature" },
  { char: "🌥️", name: "sun large cloud", keywords: ["cloud"], category: "nature" },
  { char: "☁️", name: "cloud", keywords: ["cloud"], category: "nature" },
  { char: "🌦️", name: "sun rain", keywords: ["rain", "sun"], category: "nature" },
  { char: "🌧️", name: "rain cloud", keywords: ["rain"], category: "nature" },
  { char: "⛈️", name: "thunderstorm", keywords: ["storm", "rain"], category: "nature" },
  { char: "🌩️", name: "lightning cloud", keywords: ["thunder"], category: "nature" },
  { char: "🌨️", name: "snow cloud", keywords: ["snow"], category: "nature" },
  { char: "❄️", name: "snowflake", keywords: ["snow", "cold"], category: "nature" },
  { char: "☃️", name: "snowman", keywords: ["snow", "winter"], category: "nature" },
  { char: "⛄️", name: "snowman no snow", keywords: ["snow"], category: "nature" },
  { char: "🌬️", name: "wind", keywords: ["wind"], category: "nature" },
  { char: "💨", name: "dash", keywords: ["wind", "fast"], category: "nature" },
  { char: "🌪️", name: "tornado", keywords: ["tornado", "storm"], category: "nature" },
  { char: "🌫️", name: "fog", keywords: ["fog"], category: "nature" },
  { char: "🌊", name: "wave", keywords: ["wave", "ocean", "water"], category: "nature" },
  { char: "💧", name: "drop", keywords: ["water", "drop"], category: "nature" },
  { char: "💦", name: "sweat drops", keywords: ["water", "splash"], category: "nature" },
  { char: "☔️", name: "umbrella rain", keywords: ["rain", "umbrella"], category: "nature" },
  { char: "🌈", name: "rainbow", keywords: ["rainbow", "pride"], category: "nature" },
  { char: "⚡️", name: "bolt", keywords: ["lightning", "fast"], category: "nature" },
  { char: "🔥", name: "fire", keywords: ["fire", "lit", "hot"], category: "nature" },
  { char: "💥", name: "boom", keywords: ["explosion", "boom"], category: "nature" },
  { char: "☄️", name: "comet", keywords: ["comet", "space"], category: "nature" },
  { char: "🌹", name: "rose", keywords: ["rose", "flower"], category: "nature" },
  { char: "🌷", name: "tulip", keywords: ["tulip", "flower"], category: "nature" },
  { char: "🌸", name: "cherry blossom", keywords: ["flower", "spring"], category: "nature" },
  { char: "🌺", name: "hibiscus", keywords: ["flower"], category: "nature" },
  { char: "🌼", name: "blossom", keywords: ["flower"], category: "nature" },
  { char: "🌻", name: "sunflower", keywords: ["sunflower", "flower"], category: "nature" },
  { char: "🪷", name: "lotus", keywords: ["lotus", "flower"], category: "nature" },
  { char: "🌳", name: "tree", keywords: ["tree", "plant"], category: "nature" },
  { char: "🌲", name: "evergreen", keywords: ["tree", "evergreen"], category: "nature" },
  { char: "🌴", name: "palm tree", keywords: ["palm", "tropical"], category: "nature" },
  { char: "🌵", name: "cactus", keywords: ["cactus", "desert"], category: "nature" },
  { char: "🌾", name: "wheat", keywords: ["wheat", "rice"], category: "nature" },
  { char: "🌿", name: "herb", keywords: ["herb", "plant"], category: "nature" },
  { char: "☘️", name: "shamrock", keywords: ["clover", "irish"], category: "nature" },
  { char: "🍀", name: "four leaf", keywords: ["clover", "luck"], category: "nature" },
  { char: "🍂", name: "leaves", keywords: ["leaves", "autumn", "fall"], category: "nature" },
  { char: "🍁", name: "maple", keywords: ["maple", "leaf", "canada"], category: "nature" },
  { char: "🍃", name: "leaves wind", keywords: ["leaves"], category: "nature" },
  { char: "🪴", name: "potted plant", keywords: ["plant", "pot"], category: "nature" },

  // ---------- Symbols ----------
  { char: "✅", name: "check", keywords: ["yes", "ok", "done"], category: "symbols" },
  { char: "☑️", name: "ballot check", keywords: ["check"], category: "symbols" },
  { char: "✔️", name: "tick", keywords: ["check", "yes"], category: "symbols" },
  { char: "❌", name: "cross", keywords: ["no", "wrong", "x"], category: "symbols" },
  { char: "❎", name: "negative squared", keywords: ["no"], category: "symbols" },
  { char: "⚠️", name: "warning", keywords: ["warning", "caution"], category: "symbols" },
  { char: "🚫", name: "no entry", keywords: ["banned", "no"], category: "symbols" },
  { char: "❗️", name: "exclamation", keywords: ["important", "alert"], category: "symbols" },
  { char: "❓", name: "question", keywords: ["question", "huh"], category: "symbols" },
  { char: "❔", name: "white question", keywords: ["question"], category: "symbols" },
  { char: "❕", name: "white exclamation", keywords: ["alert"], category: "symbols" },
  { char: "💯", name: "hundred", keywords: ["100", "perfect"], category: "symbols" },
  { char: "🔥", name: "fire badge", keywords: ["lit", "hot"], category: "symbols" },
  { char: "⏯️", name: "play pause", keywords: ["play", "pause"], category: "symbols" },
  { char: "▶️", name: "play", keywords: ["play", "start"], category: "symbols" },
  { char: "⏸️", name: "pause", keywords: ["pause"], category: "symbols" },
  { char: "⏹️", name: "stop", keywords: ["stop"], category: "symbols" },
  { char: "⏺️", name: "record", keywords: ["record"], category: "symbols" },
  { char: "⏭️", name: "next track", keywords: ["next"], category: "symbols" },
  { char: "⏮️", name: "prev track", keywords: ["previous"], category: "symbols" },
  { char: "⏩", name: "fast forward", keywords: ["forward"], category: "symbols" },
  { char: "⏪", name: "rewind", keywords: ["rewind"], category: "symbols" },
  { char: "🔁", name: "repeat", keywords: ["loop", "repeat"], category: "symbols" },
  { char: "🔂", name: "repeat one", keywords: ["loop one"], category: "symbols" },
  { char: "🔀", name: "shuffle", keywords: ["random"], category: "symbols" },
  { char: "🔼", name: "up button", keywords: ["up"], category: "symbols" },
  { char: "🔽", name: "down button", keywords: ["down"], category: "symbols" },
  { char: "⬆️", name: "up arrow", keywords: ["up"], category: "symbols" },
  { char: "⬇️", name: "down arrow", keywords: ["down"], category: "symbols" },
  { char: "⬅️", name: "left arrow", keywords: ["left"], category: "symbols" },
  { char: "➡️", name: "right arrow", keywords: ["right"], category: "symbols" },
  { char: "↩️", name: "right hook", keywords: ["return"], category: "symbols" },
  { char: "↪️", name: "left hook", keywords: ["forward"], category: "symbols" },
  { char: "🔃", name: "clockwise reload", keywords: ["refresh"], category: "symbols" },
  { char: "🔄", name: "counterclockwise", keywords: ["refresh", "back"], category: "symbols" },
  { char: "🔔", name: "bell", keywords: ["bell", "notify"], category: "symbols" },
  { char: "🔕", name: "bell off", keywords: ["mute", "silent"], category: "symbols" },
  { char: "🎶", name: "musical notes", keywords: ["music"], category: "symbols" },
  { char: "♻️", name: "recycle", keywords: ["recycle", "green"], category: "symbols" },
  { char: "♾️", name: "infinity", keywords: ["infinity"], category: "symbols" },
  { char: "🔱", name: "trident", keywords: ["trident"], category: "symbols" },
  { char: "⚛️", name: "atom", keywords: ["atom", "science"], category: "symbols" },
  { char: "☮️", name: "peace symbol", keywords: ["peace"], category: "symbols" },
  { char: "☯️", name: "yin yang", keywords: ["balance"], category: "symbols" },
  { char: "🆗", name: "ok button", keywords: ["ok"], category: "symbols" },
  { char: "🆕", name: "new", keywords: ["new"], category: "symbols" },
  { char: "🆓", name: "free", keywords: ["free"], category: "symbols" },
  { char: "🆙", name: "up button text", keywords: ["up"], category: "symbols" },
  { char: "🔠", name: "letters caps", keywords: ["letters", "uppercase"], category: "symbols" },
  { char: "🔡", name: "letters lower", keywords: ["letters", "lowercase"], category: "symbols" },
  { char: "🔢", name: "numbers", keywords: ["numbers"], category: "symbols" },
  { char: "🔣", name: "symbols", keywords: ["symbols"], category: "symbols" },
  { char: "🔤", name: "abc", keywords: ["letters", "abc"], category: "symbols" },
  { char: "©️", name: "copyright", keywords: ["copyright"], category: "symbols" },
  { char: "®️", name: "registered", keywords: ["registered"], category: "symbols" },
  { char: "™️", name: "trademark", keywords: ["trademark"], category: "symbols" },
  { char: "➕", name: "plus", keywords: ["plus", "add"], category: "symbols" },
  { char: "➖", name: "minus", keywords: ["minus", "subtract"], category: "symbols" },
  { char: "➗", name: "divide", keywords: ["divide"], category: "symbols" },
  { char: "✖️", name: "multiply", keywords: ["multiply", "x"], category: "symbols" },
  { char: "🟰", name: "equals", keywords: ["equals"], category: "symbols" },
  { char: "💲", name: "dollar sign", keywords: ["dollar"], category: "symbols" },
];

export function searchEmojis(query: string, category: Category | "all"): EmojiEntry[] {
  const q = query.trim().toLowerCase();
  // Strip surrounding ":" so :fire: matches the same as fire.
  const stripped = q.replace(/^:|:$/g, "");
  const pool = category === "all" ? EMOJIS : EMOJIS.filter((e) => e.category === category);
  if (!stripped) return pool;
  return pool.filter((e) => {
    if (e.name.includes(stripped)) return true;
    if (e.keywords.some((k) => k.includes(stripped))) return true;
    return false;
  });
}
